version: '3'
services:
  dash_app:
    build: ./dash_leaflet
    restart: always
    env_file: .env
    ports:
      - 8050:8050
  dash_nginx: 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - dash_app
  titiler:
    image: ghcr.io/developmentseed/titiler:latest
    ports:
      - "8000:8000"