services:
  dash_app:
    build: ./app
    restart: always
    env_file: ./app/.env
    ports:
      - 8050:8050
    depends_on:
      - titiler
  dash_nginx: 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - dash_app
  titiler:
    image: ghcr.io/developmentseed/titiler:latest
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    platform: linux/amd64