version = 0.1

[default.deploy.parameters]
stack_name = "uw-crl-api-stack"
s3_bucket = "uw-climaterisklab-api-deployment"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
no_fail_on_empty_changeset = true
template_file = "out.yml"
parameter_overrides = """
    SecurityGroupId=sg-0439a230559d3b71a
    SubnetIds="subnet-06f63a67d0f45a39d"
    S3BUCKET=uw-climaterisklab
    S3BASEPREFIXUSERDOWNLOADS=climate-risk-map/api/v1/user-downloads/
    DATASIZERETURNLIMITMB=5.9
    PGDBNAME=/api/v1/db_name
    PGUSER=/api/v1/db_user
    PGPASSWORD=/api/v1/db_pw
    PGHOST=/api/v1/db_host
"""