name: database/v1/etl/exposure/nasa-nex CI-CD

on:
  push:
    branches: [ "main" ]
    paths: [ "database/v1/etl/exposure/nasa_nex/**" ]
  
  pull_request:
    branches: [ "main" ]
    paths: [ "database/v1/etl/exposure/nasa_nex/**" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "database/v1/etl/exposure/nasa_nex/uv.lock"

      - name: Enable caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "database/v1/etl/exposure/nasa_nex/uv.lock"

      - name: Install the project
        run: |
          cd database/v1/etl/exposure/nasa_nex
          uv sync --all-extras --dev

      - name: Run tests
        run: |
          cd database/v1/etl/exposure/nasa_nex
          uv run pytest tests

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Docker Buildx # Required for advanced caching
        uses: docker/setup-buildx-action@v3

      - name: Build and cache Docker image
        uses: docker/build-push-action@v6
        with:
          context: database/v1/etl/exposure/nasa_nex
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max