name: Docker build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Builds frontend/app
      run: docker build ./frontend/app --file Dockerfile --tag /climate-risk-map/frontend/app