name: Docker build

on:
  push:
    branches: [ "main" ]
    paths: [ "frontend/app/**" ]
  
  pull_request:
    branches: [ "main" ]
    paths: [ "frontend/app/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Builds frontend/app
      run: docker build --tag frontend/app:$(date +%s) ./frontend/app